---
title: "Curriculum Vitae"
---

Download my full CV in PDF [here](/pdf/mtejadaCV.pdf).

#### Education

- Ph.D. in Economics: Georgetown University. 2013.
- M.A. in Economics: ILADES/Georgetown University. 2005.
- B.S. in Economics: Universidad Católica Boliviana. 2002.

#### Positions and Affiliations

- 2023 - present. Associate Professor. Department of Economics. Universidad Diego Portales. Santiago, Chile.
- 2013 – 2022. Assistant Professor. Department of Economics. Universidad Alberto Hurtado. Santiago, Chile.
- 2021 - 2022. Director of the Master Program in Economics (MAE). Department of Economics. Universidad Alberto Hurtado. Santiago, Chile. 

#### Research Grants

- Millenium Nucleus for Labor Market Mismatch: Causes and Consequences 2022-2024
- FONDECYT Research Grant - Selection for the Initiation of Research 2019-2022
- Konrad Adenauer Foundation Research Grants. 2017 and 2018.

#### Seminar and Conferences

- 2023: Bolivian Conference on Development Economics 2023, LACEA-LAMES Annual Meeting 2023, Annual Meeting of the Chilean Society of Economists 2023 (SECHI), Society of Economic Dynamics Annual Meeting 2023, FEN Universidad de Chile Academic Seminar, Pontificia Universidad Católica de Chile Academic Seminar, Universidad Católica Boliviana Academic Seminar.
- 2022: Bolivian Conference on Development Economics, LACEA-LAMES Annual Meeting, The Economics of Informality Conference, Pontificia Universidad Javeriana de Colombia Academic Seminar, Annual Meeting of the Chilean Society of Economists (SECHI), Universidad Diego Portales Academic Seminar, Universidad Alberto Hurtado - Universidad Andrés Bello Academic Seminar.
- 2021: Pontiﬁcia Universidad Javeriana de Colombia Academic Seminar.
- 2020: Universidad Diego Portales Academic Seminar.
- 2019: Pontiﬁcia Universidad Católica de Chile Academic Seminar. University of Sao Paulo (USP) Academic Seminar.
- 2018: 7th Workshop in Economic Development, 2018 MIPP Workshop in Macroeconomics, 9th Bolivian Conference on Development Economics, Universidad Diego Portales Academic Seminar, LACEA-LAMES Annual Meeting, 30th EALE Conference,Annual Meeting of the Chilean Society of Economists (SECHI), FEN Universidad de Chile Academic Seminar, The Economics of Informality Conference.
- 2017: 8th Bolivian Conference on Development Economics, FEN Universidad de Chile Academic Seminar, Pontificia Universidad Católica de Chile Academic Seminar, Central Bank of Chile Macroeconomics and Finance Seminar.
- 2016: LACEA-LAMES Annual Meeting, Annual Meeting of the Chilean Society of Economists (SECHI), 7th Bolivian Conference on Development Economics, Universidad Católica Boliviana Academic Seminar, Universidad Mayor de San Andrés Academic Seminar.
- 2015: LACEA Annual Meeting,Annual Meeting of the Chilean Society of Economists (SECHI), SMAUG Workshop on Search and Matching.
- 2014: LACEA-LAMES Annual Meeting, CEA Universidad de Chile Academic Seminar, Annual Meeting of the Chilean Society of Economists (SECHI), Superintendencia de Pensiones Seminar, Universidad Adolfo Ibañez Academic Seminar, Universidad de Santiago Academic Seminar, FEN Universidad de Chile Academic Seminar, 2nd Meeting LACEA Labor Network, 2nd Workshop on Economic Development (Pontificia Universidad Católica de Chile), 5th Annual Meeting of the Chilean Society of Public Policy.
- 2013: 5th Bolivian Conference on Development Economics, Pontificia Universidad Católica de Chile Academic Seminar, ILADES/Universidad Alberto Hurtado Academic Seminar, Universidad Mayor Academic Seminar, Central Bank of Chile Macroeconomics and Finance Seminar.
- 2012: Georgetown University Microeconomics Seminar.
- 2007: Eleventh Annual Conference of the Central Bank of Chile, Pontificia Universidad Católica de Chile Academic Seminar, FEN Universidad de Chile Academic Seminar, Annual Meeting LACEA-LAMES.

#### Referee Reports

- *Journals:* European Economic Review, Journal of Economic Dynamics and Control, Economic Journal, Journal of Money Credit and Banking, Journal of Macroeconomics, Labour Economics, Labour, Southern Economic Journal, Economic Analysis Review.
- *Institutions:* National Commission for Scientific and Technological Research (CONICYT – Chile).
- *Conferences:* BCDE 2016, 2017, 2018 and 2019. LACEA Annual Meeting 2015 and 2019.

#### Other Professional Activities

- Board Member of the Bolivian Society of Economists 2015/2016 and 2020/2021 ([SEBOL](http://www.sebol.org/)).
- Board Member of the Chilean Society of Economists 2022/2023 ([SECHI](https://www.sechi.cl))
